spring:
  application:
    name: data-financial
  main:
    allow-bean-definition-overriding: true

  datasource:
    mysql:
      # test
      jdbc-url: jdbc:mysql://192.168.11.11:3306/
      username: mariadb
      password: Mariadb1234!@#$
      #
      # jdbc-url: jdbc:mysql://127.0.0.1:3306/
      # username: dbadm
      # password: dbadmin123$
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10


#logging:
#  level:
#    org.spring.springboot.dao: debug
#    org.springframework.log: debug
#    com.drplant: debug
#
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl